// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zookeeper.proto

package zookeeper

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RpcKeeperException int32

const (
	RpcKeeperException_Ok                                RpcKeeperException = 0
	RpcKeeperException_SystemError                       RpcKeeperException = 1
	RpcKeeperException_RuntimeInconsistencyError         RpcKeeperException = 2
	RpcKeeperException_DataInconsistencyError            RpcKeeperException = 3
	RpcKeeperException_ConnectionLossError               RpcKeeperException = 4
	RpcKeeperException_MarshallingError                  RpcKeeperException = 5
	RpcKeeperException_UnimplementedError                RpcKeeperException = 6
	RpcKeeperException_OperationTimeoutError             RpcKeeperException = 7
	RpcKeeperException_NewConfigNoQuorumError            RpcKeeperException = 8
	RpcKeeperException_ReconfigInProgressError           RpcKeeperException = 9
	RpcKeeperException_BadArgumentsError                 RpcKeeperException = 10
	RpcKeeperException_ApiError                          RpcKeeperException = 11
	RpcKeeperException_NoNodeError                       RpcKeeperException = 12
	RpcKeeperException_NoAuthError                       RpcKeeperException = 13
	RpcKeeperException_BadVersionError                   RpcKeeperException = 14
	RpcKeeperException_NoChildrenForEphemeralsError      RpcKeeperException = 15
	RpcKeeperException_NodeExistsError                   RpcKeeperException = 16
	RpcKeeperException_InvalidAclError                   RpcKeeperException = 17
	RpcKeeperException_AuthFailedError                   RpcKeeperException = 18
	RpcKeeperException_NotEmptyError                     RpcKeeperException = 19
	RpcKeeperException_SessionExpiredError               RpcKeeperException = 20
	RpcKeeperException_InvalidCallbackError              RpcKeeperException = 21
	RpcKeeperException_SessionMovedError                 RpcKeeperException = 22
	RpcKeeperException_NotReadonlyError                  RpcKeeperException = 23
	RpcKeeperException_EphemeralOnLocalSessionError      RpcKeeperException = 24
	RpcKeeperException_NoWatcherError                    RpcKeeperException = 25
	RpcKeeperException_ReconfigDisabledError             RpcKeeperException = 26
	RpcKeeperException_SessionClosedRequireSaslAuthError RpcKeeperException = 27
	RpcKeeperException_RequestTimeoutError               RpcKeeperException = 28
	RpcKeeperException_UnknownSessionError               RpcKeeperException = 29
)

var RpcKeeperException_name = map[int32]string{
	0:  "Ok",
	1:  "SystemError",
	2:  "RuntimeInconsistencyError",
	3:  "DataInconsistencyError",
	4:  "ConnectionLossError",
	5:  "MarshallingError",
	6:  "UnimplementedError",
	7:  "OperationTimeoutError",
	8:  "NewConfigNoQuorumError",
	9:  "ReconfigInProgressError",
	10: "BadArgumentsError",
	11: "ApiError",
	12: "NoNodeError",
	13: "NoAuthError",
	14: "BadVersionError",
	15: "NoChildrenForEphemeralsError",
	16: "NodeExistsError",
	17: "InvalidAclError",
	18: "AuthFailedError",
	19: "NotEmptyError",
	20: "SessionExpiredError",
	21: "InvalidCallbackError",
	22: "SessionMovedError",
	23: "NotReadonlyError",
	24: "EphemeralOnLocalSessionError",
	25: "NoWatcherError",
	26: "ReconfigDisabledError",
	27: "SessionClosedRequireSaslAuthError",
	28: "RequestTimeoutError",
	29: "UnknownSessionError",
}

var RpcKeeperException_value = map[string]int32{
	"Ok":                                0,
	"SystemError":                       1,
	"RuntimeInconsistencyError":         2,
	"DataInconsistencyError":            3,
	"ConnectionLossError":               4,
	"MarshallingError":                  5,
	"UnimplementedError":                6,
	"OperationTimeoutError":             7,
	"NewConfigNoQuorumError":            8,
	"ReconfigInProgressError":           9,
	"BadArgumentsError":                 10,
	"ApiError":                          11,
	"NoNodeError":                       12,
	"NoAuthError":                       13,
	"BadVersionError":                   14,
	"NoChildrenForEphemeralsError":      15,
	"NodeExistsError":                   16,
	"InvalidAclError":                   17,
	"AuthFailedError":                   18,
	"NotEmptyError":                     19,
	"SessionExpiredError":               20,
	"InvalidCallbackError":              21,
	"SessionMovedError":                 22,
	"NotReadonlyError":                  23,
	"EphemeralOnLocalSessionError":      24,
	"NoWatcherError":                    25,
	"ReconfigDisabledError":             26,
	"SessionClosedRequireSaslAuthError": 27,
	"RequestTimeoutError":               28,
	"UnknownSessionError":               29,
}

func (x RpcKeeperException) String() string {
	return proto.EnumName(RpcKeeperException_name, int32(x))
}

func (RpcKeeperException) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{0}
}

type RpcKeeperState int32

const (
	RpcKeeperState_Disconnected      RpcKeeperState = 0
	RpcKeeperState_SyncConnected     RpcKeeperState = 1
	RpcKeeperState_AuthFailed        RpcKeeperState = 2
	RpcKeeperState_ConnectedReadOnly RpcKeeperState = 3
	RpcKeeperState_SaslAuthenticated RpcKeeperState = 4
	RpcKeeperState_Expired           RpcKeeperState = 5
	RpcKeeperState_Closed            RpcKeeperState = 6
)

var RpcKeeperState_name = map[int32]string{
	0: "Disconnected",
	1: "SyncConnected",
	2: "AuthFailed",
	3: "ConnectedReadOnly",
	4: "SaslAuthenticated",
	5: "Expired",
	6: "Closed",
}

var RpcKeeperState_value = map[string]int32{
	"Disconnected":      0,
	"SyncConnected":     1,
	"AuthFailed":        2,
	"ConnectedReadOnly": 3,
	"SaslAuthenticated": 4,
	"Expired":           5,
	"Closed":            6,
}

func (x RpcKeeperState) String() string {
	return proto.EnumName(RpcKeeperState_name, int32(x))
}

func (RpcKeeperState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{1}
}

type RpcEventType int32

const (
	RpcEventType_None                   RpcEventType = 0
	RpcEventType_NodeCreated            RpcEventType = 1
	RpcEventType_NodeDeleted            RpcEventType = 2
	RpcEventType_NodeDataChanged        RpcEventType = 3
	RpcEventType_NodeChildrenChanged    RpcEventType = 4
	RpcEventType_DataWatchRemoved       RpcEventType = 5
	RpcEventType_ChildWatchRemoved      RpcEventType = 6
	RpcEventType_PersistentWatchRemoved RpcEventType = 7
)

var RpcEventType_name = map[int32]string{
	0: "None",
	1: "NodeCreated",
	2: "NodeDeleted",
	3: "NodeDataChanged",
	4: "NodeChildrenChanged",
	5: "DataWatchRemoved",
	6: "ChildWatchRemoved",
	7: "PersistentWatchRemoved",
}

var RpcEventType_value = map[string]int32{
	"None":                   0,
	"NodeCreated":            1,
	"NodeDeleted":            2,
	"NodeDataChanged":        3,
	"NodeChildrenChanged":    4,
	"DataWatchRemoved":       5,
	"ChildWatchRemoved":      6,
	"PersistentWatchRemoved": 7,
}

func (x RpcEventType) String() string {
	return proto.EnumName(RpcEventType_name, int32(x))
}

func (RpcEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{2}
}

type RpcWatcherType int32

const (
	RpcWatcherType_Children RpcWatcherType = 0
	RpcWatcherType_Data     RpcWatcherType = 1
	RpcWatcherType_Any      RpcWatcherType = 2
)

var RpcWatcherType_name = map[int32]string{
	0: "Children",
	1: "Data",
	2: "Any",
}

var RpcWatcherType_value = map[string]int32{
	"Children": 0,
	"Data":     1,
	"Any":      2,
}

func (x RpcWatcherType) String() string {
	return proto.EnumName(RpcWatcherType_name, int32(x))
}

func (RpcWatcherType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{3}
}

type RpcCreateMode int32

const (
	RpcCreateMode_Persistent                  RpcCreateMode = 0
	RpcCreateMode_PersistentSequential        RpcCreateMode = 1
	RpcCreateMode_Ephemeral                   RpcCreateMode = 2
	RpcCreateMode_EphemeralSequential         RpcCreateMode = 3
	RpcCreateMode_Container                   RpcCreateMode = 4
	RpcCreateMode_PersistentWithTtl           RpcCreateMode = 5
	RpcCreateMode_PersistentSequentialWithTtl RpcCreateMode = 6
)

var RpcCreateMode_name = map[int32]string{
	0: "Persistent",
	1: "PersistentSequential",
	2: "Ephemeral",
	3: "EphemeralSequential",
	4: "Container",
	5: "PersistentWithTtl",
	6: "PersistentSequentialWithTtl",
}

var RpcCreateMode_value = map[string]int32{
	"Persistent":                  0,
	"PersistentSequential":        1,
	"Ephemeral":                   2,
	"EphemeralSequential":         3,
	"Container":                   4,
	"PersistentWithTtl":           5,
	"PersistentSequentialWithTtl": 6,
}

func (x RpcCreateMode) String() string {
	return proto.EnumName(RpcCreateMode_name, int32(x))
}

func (RpcCreateMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{4}
}

type RpcPerms int32

const (
	RpcPerms_Read   RpcPerms = 0
	RpcPerms_Write  RpcPerms = 1
	RpcPerms_Create RpcPerms = 2
	RpcPerms_Delete RpcPerms = 3
	RpcPerms_Admin  RpcPerms = 4
	RpcPerms_All    RpcPerms = 5
)

var RpcPerms_name = map[int32]string{
	0: "Read",
	1: "Write",
	2: "Create",
	3: "Delete",
	4: "Admin",
	5: "All",
}

var RpcPerms_value = map[string]int32{
	"Read":   0,
	"Write":  1,
	"Create": 2,
	"Delete": 3,
	"Admin":  4,
	"All":    5,
}

func (x RpcPerms) String() string {
	return proto.EnumName(RpcPerms_name, int32(x))
}

func (RpcPerms) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{5}
}

type RpcWatchedEvent struct {
	KeeperState          RpcKeeperState `protobuf:"varint,1,opt,name=keeperState,proto3,enum=zookeeper.RpcKeeperState" json:"keeperState,omitempty"`
	EventType            RpcEventType   `protobuf:"varint,2,opt,name=eventType,proto3,enum=zookeeper.RpcEventType" json:"eventType,omitempty"`
	Path                 string         `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RpcWatchedEvent) Reset()         { *m = RpcWatchedEvent{} }
func (m *RpcWatchedEvent) String() string { return proto.CompactTextString(m) }
func (*RpcWatchedEvent) ProtoMessage()    {}
func (*RpcWatchedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{0}
}

func (m *RpcWatchedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcWatchedEvent.Unmarshal(m, b)
}
func (m *RpcWatchedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcWatchedEvent.Marshal(b, m, deterministic)
}
func (m *RpcWatchedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcWatchedEvent.Merge(m, src)
}
func (m *RpcWatchedEvent) XXX_Size() int {
	return xxx_messageInfo_RpcWatchedEvent.Size(m)
}
func (m *RpcWatchedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcWatchedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RpcWatchedEvent proto.InternalMessageInfo

func (m *RpcWatchedEvent) GetKeeperState() RpcKeeperState {
	if m != nil {
		return m.KeeperState
	}
	return RpcKeeperState_Disconnected
}

func (m *RpcWatchedEvent) GetEventType() RpcEventType {
	if m != nil {
		return m.EventType
	}
	return RpcEventType_None
}

func (m *RpcWatchedEvent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RpcResponseHeader struct {
	Xid                  int32              `protobuf:"varint,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Zxid                 int64              `protobuf:"varint,2,opt,name=zxid,proto3" json:"zxid,omitempty"`
	Exception            RpcKeeperException `protobuf:"varint,3,opt,name=exception,proto3,enum=zookeeper.RpcKeeperException" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RpcResponseHeader) Reset()         { *m = RpcResponseHeader{} }
func (m *RpcResponseHeader) String() string { return proto.CompactTextString(m) }
func (*RpcResponseHeader) ProtoMessage()    {}
func (*RpcResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{1}
}

func (m *RpcResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResponseHeader.Unmarshal(m, b)
}
func (m *RpcResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResponseHeader.Marshal(b, m, deterministic)
}
func (m *RpcResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResponseHeader.Merge(m, src)
}
func (m *RpcResponseHeader) XXX_Size() int {
	return xxx_messageInfo_RpcResponseHeader.Size(m)
}
func (m *RpcResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResponseHeader proto.InternalMessageInfo

func (m *RpcResponseHeader) GetXid() int32 {
	if m != nil {
		return m.Xid
	}
	return 0
}

func (m *RpcResponseHeader) GetZxid() int64 {
	if m != nil {
		return m.Zxid
	}
	return 0
}

func (m *RpcResponseHeader) GetException() RpcKeeperException {
	if m != nil {
		return m.Exception
	}
	return RpcKeeperException_Ok
}

type RpcRequestHeader struct {
	Xid                  int32    `protobuf:"varint,1,opt,name=xid,proto3" json:"xid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcRequestHeader) Reset()         { *m = RpcRequestHeader{} }
func (m *RpcRequestHeader) String() string { return proto.CompactTextString(m) }
func (*RpcRequestHeader) ProtoMessage()    {}
func (*RpcRequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{2}
}

func (m *RpcRequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRequestHeader.Unmarshal(m, b)
}
func (m *RpcRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRequestHeader.Marshal(b, m, deterministic)
}
func (m *RpcRequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRequestHeader.Merge(m, src)
}
func (m *RpcRequestHeader) XXX_Size() int {
	return xxx_messageInfo_RpcRequestHeader.Size(m)
}
func (m *RpcRequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRequestHeader proto.InternalMessageInfo

func (m *RpcRequestHeader) GetXid() int32 {
	if m != nil {
		return m.Xid
	}
	return 0
}

type RpcId struct {
	Scheme               string   `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcId) Reset()         { *m = RpcId{} }
func (m *RpcId) String() string { return proto.CompactTextString(m) }
func (*RpcId) ProtoMessage()    {}
func (*RpcId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{3}
}

func (m *RpcId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcId.Unmarshal(m, b)
}
func (m *RpcId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcId.Marshal(b, m, deterministic)
}
func (m *RpcId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcId.Merge(m, src)
}
func (m *RpcId) XXX_Size() int {
	return xxx_messageInfo_RpcId.Size(m)
}
func (m *RpcId) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcId.DiscardUnknown(m)
}

var xxx_messageInfo_RpcId proto.InternalMessageInfo

func (m *RpcId) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *RpcId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RpcAcl struct {
	Perms                []RpcPerms `protobuf:"varint,1,rep,packed,name=perms,proto3,enum=zookeeper.RpcPerms" json:"perms,omitempty"`
	Id                   *RpcId     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcAcl) Reset()         { *m = RpcAcl{} }
func (m *RpcAcl) String() string { return proto.CompactTextString(m) }
func (*RpcAcl) ProtoMessage()    {}
func (*RpcAcl) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{4}
}

func (m *RpcAcl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcAcl.Unmarshal(m, b)
}
func (m *RpcAcl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcAcl.Marshal(b, m, deterministic)
}
func (m *RpcAcl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcAcl.Merge(m, src)
}
func (m *RpcAcl) XXX_Size() int {
	return xxx_messageInfo_RpcAcl.Size(m)
}
func (m *RpcAcl) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcAcl.DiscardUnknown(m)
}

var xxx_messageInfo_RpcAcl proto.InternalMessageInfo

func (m *RpcAcl) GetPerms() []RpcPerms {
	if m != nil {
		return m.Perms
	}
	return nil
}

func (m *RpcAcl) GetId() *RpcId {
	if m != nil {
		return m.Id
	}
	return nil
}

type RpcSession struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcSession) Reset()         { *m = RpcSession{} }
func (m *RpcSession) String() string { return proto.CompactTextString(m) }
func (*RpcSession) ProtoMessage()    {}
func (*RpcSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{5}
}

func (m *RpcSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSession.Unmarshal(m, b)
}
func (m *RpcSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSession.Marshal(b, m, deterministic)
}
func (m *RpcSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSession.Merge(m, src)
}
func (m *RpcSession) XXX_Size() int {
	return xxx_messageInfo_RpcSession.Size(m)
}
func (m *RpcSession) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSession.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSession proto.InternalMessageInfo

func (m *RpcSession) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type RpcStat struct {
	Czxid                int64    `protobuf:"varint,1,opt,name=czxid,proto3" json:"czxid,omitempty"`
	Mzxid                int64    `protobuf:"varint,2,opt,name=mzxid,proto3" json:"mzxid,omitempty"`
	Ctime                int64    `protobuf:"varint,3,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                int64    `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Version              int32    `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Cversion             int32    `protobuf:"varint,6,opt,name=cversion,proto3" json:"cversion,omitempty"`
	Aversion             int32    `protobuf:"varint,7,opt,name=aversion,proto3" json:"aversion,omitempty"`
	EphemeralOwner       int64    `protobuf:"varint,8,opt,name=ephemeralOwner,proto3" json:"ephemeralOwner,omitempty"`
	DataLength           int32    `protobuf:"varint,9,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	NumChildren          int32    `protobuf:"varint,10,opt,name=numChildren,proto3" json:"numChildren,omitempty"`
	Pzxid                int64    `protobuf:"varint,11,opt,name=pzxid,proto3" json:"pzxid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcStat) Reset()         { *m = RpcStat{} }
func (m *RpcStat) String() string { return proto.CompactTextString(m) }
func (*RpcStat) ProtoMessage()    {}
func (*RpcStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{6}
}

func (m *RpcStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcStat.Unmarshal(m, b)
}
func (m *RpcStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcStat.Marshal(b, m, deterministic)
}
func (m *RpcStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcStat.Merge(m, src)
}
func (m *RpcStat) XXX_Size() int {
	return xxx_messageInfo_RpcStat.Size(m)
}
func (m *RpcStat) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcStat.DiscardUnknown(m)
}

var xxx_messageInfo_RpcStat proto.InternalMessageInfo

func (m *RpcStat) GetCzxid() int64 {
	if m != nil {
		return m.Czxid
	}
	return 0
}

func (m *RpcStat) GetMzxid() int64 {
	if m != nil {
		return m.Mzxid
	}
	return 0
}

func (m *RpcStat) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *RpcStat) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *RpcStat) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RpcStat) GetCversion() int32 {
	if m != nil {
		return m.Cversion
	}
	return 0
}

func (m *RpcStat) GetAversion() int32 {
	if m != nil {
		return m.Aversion
	}
	return 0
}

func (m *RpcStat) GetEphemeralOwner() int64 {
	if m != nil {
		return m.EphemeralOwner
	}
	return 0
}

func (m *RpcStat) GetDataLength() int32 {
	if m != nil {
		return m.DataLength
	}
	return 0
}

func (m *RpcStat) GetNumChildren() int32 {
	if m != nil {
		return m.NumChildren
	}
	return 0
}

func (m *RpcStat) GetPzxid() int64 {
	if m != nil {
		return m.Pzxid
	}
	return 0
}

type RpcConnectRequest struct {
	LastZxidSeen         int64    `protobuf:"varint,1,opt,name=lastZxidSeen,proto3" json:"lastZxidSeen,omitempty"`
	TimeOut              int32    `protobuf:"varint,2,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	SessionId            int64    `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Passwd               []byte   `protobuf:"bytes,4,opt,name=passwd,proto3" json:"passwd,omitempty"`
	ReadOnly             bool     `protobuf:"varint,5,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcConnectRequest) Reset()         { *m = RpcConnectRequest{} }
func (m *RpcConnectRequest) String() string { return proto.CompactTextString(m) }
func (*RpcConnectRequest) ProtoMessage()    {}
func (*RpcConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{7}
}

func (m *RpcConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcConnectRequest.Unmarshal(m, b)
}
func (m *RpcConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcConnectRequest.Marshal(b, m, deterministic)
}
func (m *RpcConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcConnectRequest.Merge(m, src)
}
func (m *RpcConnectRequest) XXX_Size() int {
	return xxx_messageInfo_RpcConnectRequest.Size(m)
}
func (m *RpcConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcConnectRequest proto.InternalMessageInfo

func (m *RpcConnectRequest) GetLastZxidSeen() int64 {
	if m != nil {
		return m.LastZxidSeen
	}
	return 0
}

func (m *RpcConnectRequest) GetTimeOut() int32 {
	if m != nil {
		return m.TimeOut
	}
	return 0
}

func (m *RpcConnectRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RpcConnectRequest) GetPasswd() []byte {
	if m != nil {
		return m.Passwd
	}
	return nil
}

func (m *RpcConnectRequest) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type RpcConnectResponse struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	SessionTimeout       int32    `protobuf:"varint,2,opt,name=sessionTimeout,proto3" json:"sessionTimeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcConnectResponse) Reset()         { *m = RpcConnectResponse{} }
func (m *RpcConnectResponse) String() string { return proto.CompactTextString(m) }
func (*RpcConnectResponse) ProtoMessage()    {}
func (*RpcConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{8}
}

func (m *RpcConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcConnectResponse.Unmarshal(m, b)
}
func (m *RpcConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcConnectResponse.Marshal(b, m, deterministic)
}
func (m *RpcConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcConnectResponse.Merge(m, src)
}
func (m *RpcConnectResponse) XXX_Size() int {
	return xxx_messageInfo_RpcConnectResponse.Size(m)
}
func (m *RpcConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcConnectResponse proto.InternalMessageInfo

func (m *RpcConnectResponse) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RpcConnectResponse) GetSessionTimeout() int32 {
	if m != nil {
		return m.SessionTimeout
	}
	return 0
}

type RpcCreateRequest struct {
	Path                 string        `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data                 []byte        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Acl                  []*RpcAcl     `protobuf:"bytes,3,rep,name=acl,proto3" json:"acl,omitempty"`
	Mode                 RpcCreateMode `protobuf:"varint,4,opt,name=mode,proto3,enum=zookeeper.RpcCreateMode" json:"mode,omitempty"`
	Ttl                  int64         `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RpcCreateRequest) Reset()         { *m = RpcCreateRequest{} }
func (m *RpcCreateRequest) String() string { return proto.CompactTextString(m) }
func (*RpcCreateRequest) ProtoMessage()    {}
func (*RpcCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{9}
}

func (m *RpcCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcCreateRequest.Unmarshal(m, b)
}
func (m *RpcCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcCreateRequest.Marshal(b, m, deterministic)
}
func (m *RpcCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcCreateRequest.Merge(m, src)
}
func (m *RpcCreateRequest) XXX_Size() int {
	return xxx_messageInfo_RpcCreateRequest.Size(m)
}
func (m *RpcCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcCreateRequest proto.InternalMessageInfo

func (m *RpcCreateRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcCreateRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RpcCreateRequest) GetAcl() []*RpcAcl {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *RpcCreateRequest) GetMode() RpcCreateMode {
	if m != nil {
		return m.Mode
	}
	return RpcCreateMode_Persistent
}

func (m *RpcCreateRequest) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type RpcCreateResponse struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Stat                 *RpcStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcCreateResponse) Reset()         { *m = RpcCreateResponse{} }
func (m *RpcCreateResponse) String() string { return proto.CompactTextString(m) }
func (*RpcCreateResponse) ProtoMessage()    {}
func (*RpcCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{10}
}

func (m *RpcCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcCreateResponse.Unmarshal(m, b)
}
func (m *RpcCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcCreateResponse.Marshal(b, m, deterministic)
}
func (m *RpcCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcCreateResponse.Merge(m, src)
}
func (m *RpcCreateResponse) XXX_Size() int {
	return xxx_messageInfo_RpcCreateResponse.Size(m)
}
func (m *RpcCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcCreateResponse proto.InternalMessageInfo

func (m *RpcCreateResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcCreateResponse) GetStat() *RpcStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type RpcGetDataRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Watch                bool     `protobuf:"varint,2,opt,name=watch,proto3" json:"watch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetDataRequest) Reset()         { *m = RpcGetDataRequest{} }
func (m *RpcGetDataRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetDataRequest) ProtoMessage()    {}
func (*RpcGetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{11}
}

func (m *RpcGetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetDataRequest.Unmarshal(m, b)
}
func (m *RpcGetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetDataRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetDataRequest.Merge(m, src)
}
func (m *RpcGetDataRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetDataRequest.Size(m)
}
func (m *RpcGetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetDataRequest proto.InternalMessageInfo

func (m *RpcGetDataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcGetDataRequest) GetWatch() bool {
	if m != nil {
		return m.Watch
	}
	return false
}

type RpcGetDataResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stat                 *RpcStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetDataResponse) Reset()         { *m = RpcGetDataResponse{} }
func (m *RpcGetDataResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetDataResponse) ProtoMessage()    {}
func (*RpcGetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{12}
}

func (m *RpcGetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetDataResponse.Unmarshal(m, b)
}
func (m *RpcGetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetDataResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetDataResponse.Merge(m, src)
}
func (m *RpcGetDataResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetDataResponse.Size(m)
}
func (m *RpcGetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetDataResponse proto.InternalMessageInfo

func (m *RpcGetDataResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RpcGetDataResponse) GetStat() *RpcStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type RpcSetDataRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcSetDataRequest) Reset()         { *m = RpcSetDataRequest{} }
func (m *RpcSetDataRequest) String() string { return proto.CompactTextString(m) }
func (*RpcSetDataRequest) ProtoMessage()    {}
func (*RpcSetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{13}
}

func (m *RpcSetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSetDataRequest.Unmarshal(m, b)
}
func (m *RpcSetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSetDataRequest.Marshal(b, m, deterministic)
}
func (m *RpcSetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSetDataRequest.Merge(m, src)
}
func (m *RpcSetDataRequest) XXX_Size() int {
	return xxx_messageInfo_RpcSetDataRequest.Size(m)
}
func (m *RpcSetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSetDataRequest proto.InternalMessageInfo

func (m *RpcSetDataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcSetDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RpcSetDataRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RpcSetDataResponse struct {
	Stat                 *RpcStat `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcSetDataResponse) Reset()         { *m = RpcSetDataResponse{} }
func (m *RpcSetDataResponse) String() string { return proto.CompactTextString(m) }
func (*RpcSetDataResponse) ProtoMessage()    {}
func (*RpcSetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{14}
}

func (m *RpcSetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSetDataResponse.Unmarshal(m, b)
}
func (m *RpcSetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSetDataResponse.Marshal(b, m, deterministic)
}
func (m *RpcSetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSetDataResponse.Merge(m, src)
}
func (m *RpcSetDataResponse) XXX_Size() int {
	return xxx_messageInfo_RpcSetDataResponse.Size(m)
}
func (m *RpcSetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSetDataResponse proto.InternalMessageInfo

func (m *RpcSetDataResponse) GetStat() *RpcStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type RpcGetChildrenRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Watch                bool     `protobuf:"varint,2,opt,name=watch,proto3" json:"watch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetChildrenRequest) Reset()         { *m = RpcGetChildrenRequest{} }
func (m *RpcGetChildrenRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetChildrenRequest) ProtoMessage()    {}
func (*RpcGetChildrenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{15}
}

func (m *RpcGetChildrenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetChildrenRequest.Unmarshal(m, b)
}
func (m *RpcGetChildrenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetChildrenRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetChildrenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetChildrenRequest.Merge(m, src)
}
func (m *RpcGetChildrenRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetChildrenRequest.Size(m)
}
func (m *RpcGetChildrenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetChildrenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetChildrenRequest proto.InternalMessageInfo

func (m *RpcGetChildrenRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcGetChildrenRequest) GetWatch() bool {
	if m != nil {
		return m.Watch
	}
	return false
}

type RpcGetChildrenResponse struct {
	Children             []string `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	Stat                 *RpcStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetChildrenResponse) Reset()         { *m = RpcGetChildrenResponse{} }
func (m *RpcGetChildrenResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetChildrenResponse) ProtoMessage()    {}
func (*RpcGetChildrenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{16}
}

func (m *RpcGetChildrenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetChildrenResponse.Unmarshal(m, b)
}
func (m *RpcGetChildrenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetChildrenResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetChildrenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetChildrenResponse.Merge(m, src)
}
func (m *RpcGetChildrenResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetChildrenResponse.Size(m)
}
func (m *RpcGetChildrenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetChildrenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetChildrenResponse proto.InternalMessageInfo

func (m *RpcGetChildrenResponse) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *RpcGetChildrenResponse) GetStat() *RpcStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type RpcDeleteRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcDeleteRequest) Reset()         { *m = RpcDeleteRequest{} }
func (m *RpcDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RpcDeleteRequest) ProtoMessage()    {}
func (*RpcDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{17}
}

func (m *RpcDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcDeleteRequest.Unmarshal(m, b)
}
func (m *RpcDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RpcDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcDeleteRequest.Merge(m, src)
}
func (m *RpcDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RpcDeleteRequest.Size(m)
}
func (m *RpcDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcDeleteRequest proto.InternalMessageInfo

func (m *RpcDeleteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcDeleteRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RpcAuthInfo struct {
	Scheme               string   `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Auth                 []byte   `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcAuthInfo) Reset()         { *m = RpcAuthInfo{} }
func (m *RpcAuthInfo) String() string { return proto.CompactTextString(m) }
func (*RpcAuthInfo) ProtoMessage()    {}
func (*RpcAuthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{18}
}

func (m *RpcAuthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcAuthInfo.Unmarshal(m, b)
}
func (m *RpcAuthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcAuthInfo.Marshal(b, m, deterministic)
}
func (m *RpcAuthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcAuthInfo.Merge(m, src)
}
func (m *RpcAuthInfo) XXX_Size() int {
	return xxx_messageInfo_RpcAuthInfo.Size(m)
}
func (m *RpcAuthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcAuthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RpcAuthInfo proto.InternalMessageInfo

func (m *RpcAuthInfo) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *RpcAuthInfo) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type RpcExistsRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Watch                bool     `protobuf:"varint,2,opt,name=watch,proto3" json:"watch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcExistsRequest) Reset()         { *m = RpcExistsRequest{} }
func (m *RpcExistsRequest) String() string { return proto.CompactTextString(m) }
func (*RpcExistsRequest) ProtoMessage()    {}
func (*RpcExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{19}
}

func (m *RpcExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcExistsRequest.Unmarshal(m, b)
}
func (m *RpcExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcExistsRequest.Marshal(b, m, deterministic)
}
func (m *RpcExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcExistsRequest.Merge(m, src)
}
func (m *RpcExistsRequest) XXX_Size() int {
	return xxx_messageInfo_RpcExistsRequest.Size(m)
}
func (m *RpcExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcExistsRequest proto.InternalMessageInfo

func (m *RpcExistsRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcExistsRequest) GetWatch() bool {
	if m != nil {
		return m.Watch
	}
	return false
}

type RpcGetAclRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetAclRequest) Reset()         { *m = RpcGetAclRequest{} }
func (m *RpcGetAclRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetAclRequest) ProtoMessage()    {}
func (*RpcGetAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{20}
}

func (m *RpcGetAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetAclRequest.Unmarshal(m, b)
}
func (m *RpcGetAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetAclRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetAclRequest.Merge(m, src)
}
func (m *RpcGetAclRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetAclRequest.Size(m)
}
func (m *RpcGetAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetAclRequest proto.InternalMessageInfo

func (m *RpcGetAclRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RpcGetAclResponse struct {
	Acl                  []*RpcAcl `protobuf:"bytes,1,rep,name=acl,proto3" json:"acl,omitempty"`
	Stat                 *RpcStat  `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RpcGetAclResponse) Reset()         { *m = RpcGetAclResponse{} }
func (m *RpcGetAclResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetAclResponse) ProtoMessage()    {}
func (*RpcGetAclResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{21}
}

func (m *RpcGetAclResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetAclResponse.Unmarshal(m, b)
}
func (m *RpcGetAclResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetAclResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetAclResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetAclResponse.Merge(m, src)
}
func (m *RpcGetAclResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetAclResponse.Size(m)
}
func (m *RpcGetAclResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetAclResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetAclResponse proto.InternalMessageInfo

func (m *RpcGetAclResponse) GetAcl() []*RpcAcl {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *RpcGetAclResponse) GetStat() *RpcStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type RpcSetAclRequest struct {
	Path                 string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Acl                  []*RpcAcl `protobuf:"bytes,2,rep,name=acl,proto3" json:"acl,omitempty"`
	Version              int32     `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RpcSetAclRequest) Reset()         { *m = RpcSetAclRequest{} }
func (m *RpcSetAclRequest) String() string { return proto.CompactTextString(m) }
func (*RpcSetAclRequest) ProtoMessage()    {}
func (*RpcSetAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{22}
}

func (m *RpcSetAclRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSetAclRequest.Unmarshal(m, b)
}
func (m *RpcSetAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSetAclRequest.Marshal(b, m, deterministic)
}
func (m *RpcSetAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSetAclRequest.Merge(m, src)
}
func (m *RpcSetAclRequest) XXX_Size() int {
	return xxx_messageInfo_RpcSetAclRequest.Size(m)
}
func (m *RpcSetAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSetAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSetAclRequest proto.InternalMessageInfo

func (m *RpcSetAclRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RpcSetAclRequest) GetAcl() []*RpcAcl {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *RpcSetAclRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RpcSetAclResponse struct {
	Stat                 *RpcStat `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcSetAclResponse) Reset()         { *m = RpcSetAclResponse{} }
func (m *RpcSetAclResponse) String() string { return proto.CompactTextString(m) }
func (*RpcSetAclResponse) ProtoMessage()    {}
func (*RpcSetAclResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{23}
}

func (m *RpcSetAclResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcSetAclResponse.Unmarshal(m, b)
}
func (m *RpcSetAclResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcSetAclResponse.Marshal(b, m, deterministic)
}
func (m *RpcSetAclResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcSetAclResponse.Merge(m, src)
}
func (m *RpcSetAclResponse) XXX_Size() int {
	return xxx_messageInfo_RpcSetAclResponse.Size(m)
}
func (m *RpcSetAclResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcSetAclResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcSetAclResponse proto.InternalMessageInfo

func (m *RpcSetAclResponse) GetStat() *RpcStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type RpcGetAllChildrenNumberRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetAllChildrenNumberRequest) Reset()         { *m = RpcGetAllChildrenNumberRequest{} }
func (m *RpcGetAllChildrenNumberRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetAllChildrenNumberRequest) ProtoMessage()    {}
func (*RpcGetAllChildrenNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{24}
}

func (m *RpcGetAllChildrenNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetAllChildrenNumberRequest.Unmarshal(m, b)
}
func (m *RpcGetAllChildrenNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetAllChildrenNumberRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetAllChildrenNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetAllChildrenNumberRequest.Merge(m, src)
}
func (m *RpcGetAllChildrenNumberRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetAllChildrenNumberRequest.Size(m)
}
func (m *RpcGetAllChildrenNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetAllChildrenNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetAllChildrenNumberRequest proto.InternalMessageInfo

func (m *RpcGetAllChildrenNumberRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RpcGetAllChildrenNumberResponse struct {
	TotalNumber          int32    `protobuf:"varint,1,opt,name=totalNumber,proto3" json:"totalNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetAllChildrenNumberResponse) Reset()         { *m = RpcGetAllChildrenNumberResponse{} }
func (m *RpcGetAllChildrenNumberResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetAllChildrenNumberResponse) ProtoMessage()    {}
func (*RpcGetAllChildrenNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{25}
}

func (m *RpcGetAllChildrenNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetAllChildrenNumberResponse.Unmarshal(m, b)
}
func (m *RpcGetAllChildrenNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetAllChildrenNumberResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetAllChildrenNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetAllChildrenNumberResponse.Merge(m, src)
}
func (m *RpcGetAllChildrenNumberResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetAllChildrenNumberResponse.Size(m)
}
func (m *RpcGetAllChildrenNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetAllChildrenNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetAllChildrenNumberResponse proto.InternalMessageInfo

func (m *RpcGetAllChildrenNumberResponse) GetTotalNumber() int32 {
	if m != nil {
		return m.TotalNumber
	}
	return 0
}

type RpcGetEphemeralsRequest struct {
	PrefixPath           string   `protobuf:"bytes,1,opt,name=prefixPath,proto3" json:"prefixPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetEphemeralsRequest) Reset()         { *m = RpcGetEphemeralsRequest{} }
func (m *RpcGetEphemeralsRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetEphemeralsRequest) ProtoMessage()    {}
func (*RpcGetEphemeralsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{26}
}

func (m *RpcGetEphemeralsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetEphemeralsRequest.Unmarshal(m, b)
}
func (m *RpcGetEphemeralsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetEphemeralsRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetEphemeralsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetEphemeralsRequest.Merge(m, src)
}
func (m *RpcGetEphemeralsRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetEphemeralsRequest.Size(m)
}
func (m *RpcGetEphemeralsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetEphemeralsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetEphemeralsRequest proto.InternalMessageInfo

func (m *RpcGetEphemeralsRequest) GetPrefixPath() string {
	if m != nil {
		return m.PrefixPath
	}
	return ""
}

type RpcGetEphemeralsResponse struct {
	Ephemerals           []string `protobuf:"bytes,1,rep,name=ephemerals,proto3" json:"ephemerals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetEphemeralsResponse) Reset()         { *m = RpcGetEphemeralsResponse{} }
func (m *RpcGetEphemeralsResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetEphemeralsResponse) ProtoMessage()    {}
func (*RpcGetEphemeralsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{27}
}

func (m *RpcGetEphemeralsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetEphemeralsResponse.Unmarshal(m, b)
}
func (m *RpcGetEphemeralsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetEphemeralsResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetEphemeralsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetEphemeralsResponse.Merge(m, src)
}
func (m *RpcGetEphemeralsResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetEphemeralsResponse.Size(m)
}
func (m *RpcGetEphemeralsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetEphemeralsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetEphemeralsResponse proto.InternalMessageInfo

func (m *RpcGetEphemeralsResponse) GetEphemerals() []string {
	if m != nil {
		return m.Ephemerals
	}
	return nil
}

type RpcRequest struct {
	Header *RpcRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Detail:
	//	*RpcRequest_Connect
	//	*RpcRequest_Create
	//	*RpcRequest_GetData
	//	*RpcRequest_SetData
	//	*RpcRequest_GetChildren
	//	*RpcRequest_Delete
	//	*RpcRequest_Auth
	//	*RpcRequest_Exists
	//	*RpcRequest_GetAcl
	//	*RpcRequest_SetAcl
	//	*RpcRequest_GetAllChildrenNumber
	//	*RpcRequest_GetEphemerals
	Detail               isRpcRequest_Detail `protobuf_oneof:"detail"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RpcRequest) Reset()         { *m = RpcRequest{} }
func (m *RpcRequest) String() string { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()    {}
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{28}
}

func (m *RpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcRequest.Unmarshal(m, b)
}
func (m *RpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcRequest.Marshal(b, m, deterministic)
}
func (m *RpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcRequest.Merge(m, src)
}
func (m *RpcRequest) XXX_Size() int {
	return xxx_messageInfo_RpcRequest.Size(m)
}
func (m *RpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcRequest proto.InternalMessageInfo

func (m *RpcRequest) GetHeader() *RpcRequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type isRpcRequest_Detail interface {
	isRpcRequest_Detail()
}

type RpcRequest_Connect struct {
	Connect *RpcConnectRequest `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type RpcRequest_Create struct {
	Create *RpcCreateRequest `protobuf:"bytes,3,opt,name=create,proto3,oneof"`
}

type RpcRequest_GetData struct {
	GetData *RpcGetDataRequest `protobuf:"bytes,4,opt,name=getData,proto3,oneof"`
}

type RpcRequest_SetData struct {
	SetData *RpcSetDataRequest `protobuf:"bytes,5,opt,name=setData,proto3,oneof"`
}

type RpcRequest_GetChildren struct {
	GetChildren *RpcGetChildrenRequest `protobuf:"bytes,6,opt,name=getChildren,proto3,oneof"`
}

type RpcRequest_Delete struct {
	Delete *RpcDeleteRequest `protobuf:"bytes,7,opt,name=delete,proto3,oneof"`
}

type RpcRequest_Auth struct {
	Auth *RpcAuthInfo `protobuf:"bytes,8,opt,name=auth,proto3,oneof"`
}

type RpcRequest_Exists struct {
	Exists *RpcExistsRequest `protobuf:"bytes,9,opt,name=exists,proto3,oneof"`
}

type RpcRequest_GetAcl struct {
	GetAcl *RpcGetAclRequest `protobuf:"bytes,10,opt,name=getAcl,proto3,oneof"`
}

type RpcRequest_SetAcl struct {
	SetAcl *RpcSetAclRequest `protobuf:"bytes,11,opt,name=setAcl,proto3,oneof"`
}

type RpcRequest_GetAllChildrenNumber struct {
	GetAllChildrenNumber *RpcGetAllChildrenNumberRequest `protobuf:"bytes,12,opt,name=getAllChildrenNumber,proto3,oneof"`
}

type RpcRequest_GetEphemerals struct {
	GetEphemerals *RpcGetEphemeralsRequest `protobuf:"bytes,13,opt,name=getEphemerals,proto3,oneof"`
}

func (*RpcRequest_Connect) isRpcRequest_Detail() {}

func (*RpcRequest_Create) isRpcRequest_Detail() {}

func (*RpcRequest_GetData) isRpcRequest_Detail() {}

func (*RpcRequest_SetData) isRpcRequest_Detail() {}

func (*RpcRequest_GetChildren) isRpcRequest_Detail() {}

func (*RpcRequest_Delete) isRpcRequest_Detail() {}

func (*RpcRequest_Auth) isRpcRequest_Detail() {}

func (*RpcRequest_Exists) isRpcRequest_Detail() {}

func (*RpcRequest_GetAcl) isRpcRequest_Detail() {}

func (*RpcRequest_SetAcl) isRpcRequest_Detail() {}

func (*RpcRequest_GetAllChildrenNumber) isRpcRequest_Detail() {}

func (*RpcRequest_GetEphemerals) isRpcRequest_Detail() {}

func (m *RpcRequest) GetDetail() isRpcRequest_Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *RpcRequest) GetConnect() *RpcConnectRequest {
	if x, ok := m.GetDetail().(*RpcRequest_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *RpcRequest) GetCreate() *RpcCreateRequest {
	if x, ok := m.GetDetail().(*RpcRequest_Create); ok {
		return x.Create
	}
	return nil
}

func (m *RpcRequest) GetGetData() *RpcGetDataRequest {
	if x, ok := m.GetDetail().(*RpcRequest_GetData); ok {
		return x.GetData
	}
	return nil
}

func (m *RpcRequest) GetSetData() *RpcSetDataRequest {
	if x, ok := m.GetDetail().(*RpcRequest_SetData); ok {
		return x.SetData
	}
	return nil
}

func (m *RpcRequest) GetGetChildren() *RpcGetChildrenRequest {
	if x, ok := m.GetDetail().(*RpcRequest_GetChildren); ok {
		return x.GetChildren
	}
	return nil
}

func (m *RpcRequest) GetDelete() *RpcDeleteRequest {
	if x, ok := m.GetDetail().(*RpcRequest_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *RpcRequest) GetAuth() *RpcAuthInfo {
	if x, ok := m.GetDetail().(*RpcRequest_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *RpcRequest) GetExists() *RpcExistsRequest {
	if x, ok := m.GetDetail().(*RpcRequest_Exists); ok {
		return x.Exists
	}
	return nil
}

func (m *RpcRequest) GetGetAcl() *RpcGetAclRequest {
	if x, ok := m.GetDetail().(*RpcRequest_GetAcl); ok {
		return x.GetAcl
	}
	return nil
}

func (m *RpcRequest) GetSetAcl() *RpcSetAclRequest {
	if x, ok := m.GetDetail().(*RpcRequest_SetAcl); ok {
		return x.SetAcl
	}
	return nil
}

func (m *RpcRequest) GetGetAllChildrenNumber() *RpcGetAllChildrenNumberRequest {
	if x, ok := m.GetDetail().(*RpcRequest_GetAllChildrenNumber); ok {
		return x.GetAllChildrenNumber
	}
	return nil
}

func (m *RpcRequest) GetGetEphemerals() *RpcGetEphemeralsRequest {
	if x, ok := m.GetDetail().(*RpcRequest_GetEphemerals); ok {
		return x.GetEphemerals
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RpcRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RpcRequest_Connect)(nil),
		(*RpcRequest_Create)(nil),
		(*RpcRequest_GetData)(nil),
		(*RpcRequest_SetData)(nil),
		(*RpcRequest_GetChildren)(nil),
		(*RpcRequest_Delete)(nil),
		(*RpcRequest_Auth)(nil),
		(*RpcRequest_Exists)(nil),
		(*RpcRequest_GetAcl)(nil),
		(*RpcRequest_SetAcl)(nil),
		(*RpcRequest_GetAllChildrenNumber)(nil),
		(*RpcRequest_GetEphemerals)(nil),
	}
}

type RpcResponse struct {
	Header *RpcResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Detail:
	//	*RpcResponse_Connect
	//	*RpcResponse_Create
	//	*RpcResponse_GetData
	//	*RpcResponse_SetData
	//	*RpcResponse_GetChildren
	//	*RpcResponse_WatchedEvent
	//	*RpcResponse_GetAcl
	//	*RpcResponse_SetAcl
	//	*RpcResponse_GetAllChildrenNumber
	//	*RpcResponse_GetEphemerals
	Detail               isRpcResponse_Detail `protobuf_oneof:"detail"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RpcResponse) Reset()         { *m = RpcResponse{} }
func (m *RpcResponse) String() string { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()    {}
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2c6cc81ad321241, []int{29}
}

func (m *RpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResponse.Unmarshal(m, b)
}
func (m *RpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResponse.Marshal(b, m, deterministic)
}
func (m *RpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResponse.Merge(m, src)
}
func (m *RpcResponse) XXX_Size() int {
	return xxx_messageInfo_RpcResponse.Size(m)
}
func (m *RpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResponse proto.InternalMessageInfo

func (m *RpcResponse) GetHeader() *RpcResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type isRpcResponse_Detail interface {
	isRpcResponse_Detail()
}

type RpcResponse_Connect struct {
	Connect *RpcConnectResponse `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type RpcResponse_Create struct {
	Create *RpcCreateResponse `protobuf:"bytes,3,opt,name=create,proto3,oneof"`
}

type RpcResponse_GetData struct {
	GetData *RpcGetDataResponse `protobuf:"bytes,4,opt,name=getData,proto3,oneof"`
}

type RpcResponse_SetData struct {
	SetData *RpcSetDataResponse `protobuf:"bytes,5,opt,name=setData,proto3,oneof"`
}

type RpcResponse_GetChildren struct {
	GetChildren *RpcGetChildrenResponse `protobuf:"bytes,6,opt,name=getChildren,proto3,oneof"`
}

type RpcResponse_WatchedEvent struct {
	WatchedEvent *RpcWatchedEvent `protobuf:"bytes,7,opt,name=watchedEvent,proto3,oneof"`
}

type RpcResponse_GetAcl struct {
	GetAcl *RpcGetAclResponse `protobuf:"bytes,8,opt,name=getAcl,proto3,oneof"`
}

type RpcResponse_SetAcl struct {
	SetAcl *RpcSetAclResponse `protobuf:"bytes,9,opt,name=setAcl,proto3,oneof"`
}

type RpcResponse_GetAllChildrenNumber struct {
	GetAllChildrenNumber *RpcGetAllChildrenNumberResponse `protobuf:"bytes,10,opt,name=getAllChildrenNumber,proto3,oneof"`
}

type RpcResponse_GetEphemerals struct {
	GetEphemerals *RpcGetEphemeralsResponse `protobuf:"bytes,13,opt,name=getEphemerals,proto3,oneof"`
}

func (*RpcResponse_Connect) isRpcResponse_Detail() {}

func (*RpcResponse_Create) isRpcResponse_Detail() {}

func (*RpcResponse_GetData) isRpcResponse_Detail() {}

func (*RpcResponse_SetData) isRpcResponse_Detail() {}

func (*RpcResponse_GetChildren) isRpcResponse_Detail() {}

func (*RpcResponse_WatchedEvent) isRpcResponse_Detail() {}

func (*RpcResponse_GetAcl) isRpcResponse_Detail() {}

func (*RpcResponse_SetAcl) isRpcResponse_Detail() {}

func (*RpcResponse_GetAllChildrenNumber) isRpcResponse_Detail() {}

func (*RpcResponse_GetEphemerals) isRpcResponse_Detail() {}

func (m *RpcResponse) GetDetail() isRpcResponse_Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *RpcResponse) GetConnect() *RpcConnectResponse {
	if x, ok := m.GetDetail().(*RpcResponse_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *RpcResponse) GetCreate() *RpcCreateResponse {
	if x, ok := m.GetDetail().(*RpcResponse_Create); ok {
		return x.Create
	}
	return nil
}

func (m *RpcResponse) GetGetData() *RpcGetDataResponse {
	if x, ok := m.GetDetail().(*RpcResponse_GetData); ok {
		return x.GetData
	}
	return nil
}

func (m *RpcResponse) GetSetData() *RpcSetDataResponse {
	if x, ok := m.GetDetail().(*RpcResponse_SetData); ok {
		return x.SetData
	}
	return nil
}

func (m *RpcResponse) GetGetChildren() *RpcGetChildrenResponse {
	if x, ok := m.GetDetail().(*RpcResponse_GetChildren); ok {
		return x.GetChildren
	}
	return nil
}

func (m *RpcResponse) GetWatchedEvent() *RpcWatchedEvent {
	if x, ok := m.GetDetail().(*RpcResponse_WatchedEvent); ok {
		return x.WatchedEvent
	}
	return nil
}

func (m *RpcResponse) GetGetAcl() *RpcGetAclResponse {
	if x, ok := m.GetDetail().(*RpcResponse_GetAcl); ok {
		return x.GetAcl
	}
	return nil
}

func (m *RpcResponse) GetSetAcl() *RpcSetAclResponse {
	if x, ok := m.GetDetail().(*RpcResponse_SetAcl); ok {
		return x.SetAcl
	}
	return nil
}

func (m *RpcResponse) GetGetAllChildrenNumber() *RpcGetAllChildrenNumberResponse {
	if x, ok := m.GetDetail().(*RpcResponse_GetAllChildrenNumber); ok {
		return x.GetAllChildrenNumber
	}
	return nil
}

func (m *RpcResponse) GetGetEphemerals() *RpcGetEphemeralsResponse {
	if x, ok := m.GetDetail().(*RpcResponse_GetEphemerals); ok {
		return x.GetEphemerals
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RpcResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RpcResponse_Connect)(nil),
		(*RpcResponse_Create)(nil),
		(*RpcResponse_GetData)(nil),
		(*RpcResponse_SetData)(nil),
		(*RpcResponse_GetChildren)(nil),
		(*RpcResponse_WatchedEvent)(nil),
		(*RpcResponse_GetAcl)(nil),
		(*RpcResponse_SetAcl)(nil),
		(*RpcResponse_GetAllChildrenNumber)(nil),
		(*RpcResponse_GetEphemerals)(nil),
	}
}

func init() {
	proto.RegisterEnum("zookeeper.RpcKeeperException", RpcKeeperException_name, RpcKeeperException_value)
	proto.RegisterEnum("zookeeper.RpcKeeperState", RpcKeeperState_name, RpcKeeperState_value)
	proto.RegisterEnum("zookeeper.RpcEventType", RpcEventType_name, RpcEventType_value)
	proto.RegisterEnum("zookeeper.RpcWatcherType", RpcWatcherType_name, RpcWatcherType_value)
	proto.RegisterEnum("zookeeper.RpcCreateMode", RpcCreateMode_name, RpcCreateMode_value)
	proto.RegisterEnum("zookeeper.RpcPerms", RpcPerms_name, RpcPerms_value)
	proto.RegisterType((*RpcWatchedEvent)(nil), "zookeeper.RpcWatchedEvent")
	proto.RegisterType((*RpcResponseHeader)(nil), "zookeeper.RpcResponseHeader")
	proto.RegisterType((*RpcRequestHeader)(nil), "zookeeper.RpcRequestHeader")
	proto.RegisterType((*RpcId)(nil), "zookeeper.RpcId")
	proto.RegisterType((*RpcAcl)(nil), "zookeeper.RpcAcl")
	proto.RegisterType((*RpcSession)(nil), "zookeeper.RpcSession")
	proto.RegisterType((*RpcStat)(nil), "zookeeper.RpcStat")
	proto.RegisterType((*RpcConnectRequest)(nil), "zookeeper.RpcConnectRequest")
	proto.RegisterType((*RpcConnectResponse)(nil), "zookeeper.RpcConnectResponse")
	proto.RegisterType((*RpcCreateRequest)(nil), "zookeeper.RpcCreateRequest")
	proto.RegisterType((*RpcCreateResponse)(nil), "zookeeper.RpcCreateResponse")
	proto.RegisterType((*RpcGetDataRequest)(nil), "zookeeper.RpcGetDataRequest")
	proto.RegisterType((*RpcGetDataResponse)(nil), "zookeeper.RpcGetDataResponse")
	proto.RegisterType((*RpcSetDataRequest)(nil), "zookeeper.RpcSetDataRequest")
	proto.RegisterType((*RpcSetDataResponse)(nil), "zookeeper.RpcSetDataResponse")
	proto.RegisterType((*RpcGetChildrenRequest)(nil), "zookeeper.RpcGetChildrenRequest")
	proto.RegisterType((*RpcGetChildrenResponse)(nil), "zookeeper.RpcGetChildrenResponse")
	proto.RegisterType((*RpcDeleteRequest)(nil), "zookeeper.RpcDeleteRequest")
	proto.RegisterType((*RpcAuthInfo)(nil), "zookeeper.RpcAuthInfo")
	proto.RegisterType((*RpcExistsRequest)(nil), "zookeeper.RpcExistsRequest")
	proto.RegisterType((*RpcGetAclRequest)(nil), "zookeeper.RpcGetAclRequest")
	proto.RegisterType((*RpcGetAclResponse)(nil), "zookeeper.RpcGetAclResponse")
	proto.RegisterType((*RpcSetAclRequest)(nil), "zookeeper.RpcSetAclRequest")
	proto.RegisterType((*RpcSetAclResponse)(nil), "zookeeper.RpcSetAclResponse")
	proto.RegisterType((*RpcGetAllChildrenNumberRequest)(nil), "zookeeper.RpcGetAllChildrenNumberRequest")
	proto.RegisterType((*RpcGetAllChildrenNumberResponse)(nil), "zookeeper.RpcGetAllChildrenNumberResponse")
	proto.RegisterType((*RpcGetEphemeralsRequest)(nil), "zookeeper.RpcGetEphemeralsRequest")
	proto.RegisterType((*RpcGetEphemeralsResponse)(nil), "zookeeper.RpcGetEphemeralsResponse")
	proto.RegisterType((*RpcRequest)(nil), "zookeeper.RpcRequest")
	proto.RegisterType((*RpcResponse)(nil), "zookeeper.RpcResponse")
}

func init() { proto.RegisterFile("zookeeper.proto", fileDescriptor_f2c6cc81ad321241) }

var fileDescriptor_f2c6cc81ad321241 = []byte{
	// 2014 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcb, 0x72, 0xdb, 0xc8,
	0xd5, 0x26, 0x48, 0x91, 0x22, 0x0f, 0x29, 0x0a, 0x6a, 0xeb, 0x42, 0xcb, 0x92, 0x47, 0x03, 0xff,
	0xbf, 0xa3, 0x51, 0xa5, 0x9c, 0x44, 0x73, 0xa9, 0x28, 0x76, 0xaa, 0x46, 0x96, 0x34, 0x23, 0xc5,
	0x36, 0xa5, 0x34, 0xed, 0x4c, 0x95, 0x2b, 0x55, 0x19, 0x18, 0x68, 0x93, 0x28, 0x83, 0xdd, 0x08,
	0xd0, 0xd4, 0xc5, 0xcf, 0x90, 0x17, 0xc8, 0x2a, 0x8b, 0x6c, 0xb2, 0xc9, 0x22, 0x95, 0xe7, 0x49,
	0x9e, 0x25, 0x75, 0xba, 0x1b, 0x20, 0xc0, 0x8b, 0xac, 0xd9, 0xa1, 0x4f, 0x9f, 0xeb, 0xd7, 0xe7,
	0x3b, 0x68, 0x00, 0x96, 0x3f, 0x0a, 0xf1, 0x81, 0xb1, 0x88, 0xc5, 0x4f, 0xa2, 0x58, 0x48, 0x41,
	0x1a, 0x99, 0xc0, 0xf9, 0xab, 0x05, 0xcb, 0x34, 0xf2, 0x7e, 0x70, 0xa5, 0x37, 0x60, 0xfe, 0xc9,
	0x25, 0xe3, 0x92, 0x3c, 0x85, 0xa6, 0xde, 0xed, 0x49, 0x57, 0xb2, 0x8e, 0xb5, 0x63, 0xed, 0xb6,
	0xf7, 0xef, 0x3f, 0x19, 0x7b, 0xa1, 0x91, 0xf7, 0x62, 0xac, 0x40, 0xf3, 0xda, 0xe4, 0x6b, 0x68,
	0x30, 0xf4, 0xf2, 0xfa, 0x26, 0x62, 0x9d, 0xb2, 0x32, 0xdd, 0x28, 0x9a, 0x9e, 0xa4, 0xdb, 0x74,
	0xac, 0x49, 0x08, 0x2c, 0x44, 0xae, 0x1c, 0x74, 0x2a, 0x3b, 0xd6, 0x6e, 0x83, 0xaa, 0x67, 0xe7,
	0x12, 0x56, 0x68, 0xe4, 0x51, 0x96, 0x44, 0x82, 0x27, 0xec, 0x94, 0xb9, 0x3e, 0x8b, 0x89, 0x0d,
	0x95, 0xeb, 0xc0, 0x57, 0x49, 0x55, 0x29, 0x3e, 0xa2, 0xe9, 0x47, 0x14, 0x61, 0xb0, 0x0a, 0x55,
	0xcf, 0xe4, 0x29, 0x34, 0xd8, 0xb5, 0xc7, 0x22, 0x19, 0x08, 0xae, 0x7c, 0xb6, 0xf7, 0xb7, 0x67,
	0x15, 0x70, 0x92, 0x2a, 0xd1, 0xb1, 0xbe, 0xf3, 0x7f, 0x60, 0xab, 0xb8, 0x7f, 0x1e, 0xb1, 0x44,
	0xce, 0x0b, 0xeb, 0xfc, 0x02, 0xaa, 0x34, 0xf2, 0xce, 0x7c, 0xb2, 0x0e, 0xb5, 0xc4, 0x1b, 0xb0,
	0xa1, 0x46, 0xaa, 0x41, 0xcd, 0x8a, 0xb4, 0xa1, 0x6c, 0xb2, 0x6a, 0xd0, 0x72, 0xe0, 0x3b, 0x6f,
	0xa0, 0x46, 0x23, 0xef, 0xd0, 0x0b, 0xc9, 0x17, 0x50, 0x8d, 0x58, 0x3c, 0x4c, 0x3a, 0xd6, 0x4e,
	0x65, 0xb7, 0xbd, 0x7f, 0xaf, 0x98, 0xd9, 0x05, 0x6e, 0x51, 0xad, 0x41, 0x76, 0x32, 0x27, 0xcd,
	0x7d, 0xbb, 0xa8, 0x77, 0xe6, 0x2b, 0xb7, 0x7b, 0x00, 0x34, 0xf2, 0x7a, 0x2c, 0x49, 0x02, 0xc1,
	0xc9, 0x16, 0x34, 0x12, 0xfd, 0x78, 0xa6, 0xb3, 0xad, 0xd0, 0xb1, 0xc0, 0xf9, 0x77, 0x19, 0x16,
	0x51, 0x59, 0xba, 0x92, 0xac, 0x42, 0xd5, 0xfb, 0x98, 0xd6, 0x54, 0xa1, 0x7a, 0x81, 0xd2, 0x61,
	0x0e, 0x4d, 0xbd, 0x50, 0xba, 0x32, 0x18, 0x32, 0x05, 0x25, 0xea, 0xe2, 0x42, 0xe9, 0x2a, 0xe9,
	0x82, 0xd1, 0x55, 0xd2, 0x0e, 0x2c, 0x5e, 0xb2, 0x18, 0x03, 0x76, 0xaa, 0x0a, 0xad, 0x74, 0x49,
	0x36, 0xa1, 0xee, 0xa5, 0x5b, 0x35, 0xb5, 0x95, 0xad, 0x71, 0xcf, 0x4d, 0xf7, 0x16, 0xf5, 0x5e,
	0xba, 0x26, 0x8f, 0xa1, 0xcd, 0x22, 0x84, 0x34, 0x76, 0xc3, 0xf3, 0x2b, 0xce, 0xe2, 0x4e, 0x5d,
	0x05, 0x9c, 0x90, 0x92, 0x87, 0x00, 0xbe, 0x2b, 0xdd, 0x97, 0x8c, 0xf7, 0xe5, 0xa0, 0xd3, 0x50,
	0x5e, 0x72, 0x12, 0xb2, 0x03, 0x4d, 0x3e, 0x1a, 0x1e, 0x0d, 0x82, 0xd0, 0x8f, 0x19, 0xef, 0x80,
	0x52, 0xc8, 0x8b, 0xb0, 0xa2, 0x48, 0x55, 0xdf, 0xd4, 0x15, 0xa9, 0x85, 0xf3, 0x77, 0x4b, 0x35,
	0xe2, 0x91, 0xe0, 0x9c, 0x79, 0xd2, 0xf4, 0x05, 0x71, 0xa0, 0x15, 0xba, 0x89, 0x7c, 0x7b, 0x1d,
	0xf8, 0x3d, 0xc6, 0xb8, 0x81, 0xb1, 0x20, 0x43, 0x2c, 0x10, 0x93, 0xf3, 0x91, 0x54, 0x78, 0x56,
	0x69, 0xba, 0x2c, 0x9e, 0x53, 0x65, 0xe2, 0x9c, 0xb0, 0xa5, 0x22, 0x37, 0x49, 0xae, 0x7c, 0x05,
	0x6d, 0x8b, 0x9a, 0x15, 0xa2, 0x14, 0x33, 0xd7, 0x3f, 0xe7, 0xe1, 0x8d, 0x02, 0xb7, 0x4e, 0xb3,
	0xb5, 0xf3, 0x16, 0x48, 0x3e, 0x49, 0x4d, 0x9a, 0xdb, 0xfb, 0x01, 0x91, 0x35, 0x8b, 0xd7, 0xc1,
	0x90, 0x89, 0x2c, 0xcd, 0x09, 0xa9, 0xf3, 0x37, 0x4b, 0x51, 0xe2, 0x28, 0x66, 0xc8, 0x77, 0x03,
	0x40, 0x4a, 0x59, 0x6b, 0x4c, 0x59, 0x94, 0x21, 0xe0, 0xca, 0x4d, 0x8b, 0xaa, 0x67, 0xf2, 0x08,
	0x2a, 0xae, 0x17, 0x76, 0x2a, 0x3b, 0x95, 0xdd, 0xe6, 0xfe, 0x4a, 0xb1, 0x87, 0x0f, 0xbd, 0x90,
	0xe2, 0x2e, 0xf9, 0x39, 0x2c, 0x0c, 0x85, 0xaf, 0x5b, 0xa9, 0xbd, 0xdf, 0x29, 0x6a, 0xe9, 0xb8,
	0xaf, 0x84, 0xcf, 0xa8, 0xd2, 0x42, 0x36, 0x4a, 0x19, 0x2a, 0x08, 0x2a, 0x14, 0x1f, 0x9d, 0x73,
	0x7d, 0x44, 0x26, 0x41, 0x53, 0xfc, 0xac, 0x0c, 0x1f, 0xc3, 0x42, 0x22, 0x5d, 0x69, 0x28, 0x45,
	0x8a, 0x81, 0x90, 0x18, 0x54, 0xed, 0x3b, 0xbf, 0x55, 0x0e, 0xbf, 0x67, 0xf2, 0xd8, 0x95, 0xee,
	0x6d, 0x25, 0xaf, 0x42, 0xf5, 0x0a, 0xa7, 0xa7, 0xf2, 0x58, 0xa7, 0x7a, 0xe1, 0x5c, 0xa8, 0xd3,
	0xc8, 0xcc, 0xc7, 0x09, 0x29, 0x78, 0xac, 0x1c, 0x3c, 0x77, 0x4d, 0xe8, 0x8d, 0x4a, 0xa8, 0xf7,
	0xe9, 0x84, 0x66, 0x9d, 0x41, 0x8e, 0x94, 0x95, 0x02, 0x29, 0x9d, 0x67, 0x2a, 0xd1, 0xde, 0x44,
	0xa2, 0x69, 0x52, 0xd6, 0x27, 0x92, 0x3a, 0x84, 0x35, 0x5d, 0x66, 0x4a, 0xa1, 0x9f, 0x8e, 0xd4,
	0x1f, 0x61, 0x7d, 0xd2, 0x85, 0x49, 0x02, 0xe7, 0x45, 0x4a, 0x56, 0x9c, 0x94, 0x0d, 0x9a, 0xad,
	0xef, 0x8c, 0xda, 0xb7, 0xaa, 0x71, 0x8f, 0x59, 0xc8, 0x6e, 0x6f, 0xdc, 0x1c, 0x40, 0xe5, 0x22,
	0x40, 0x07, 0xd0, 0xc4, 0x46, 0x1d, 0xc9, 0xc1, 0x19, 0x7f, 0x2f, 0xe6, 0x4e, 0x7b, 0x02, 0x0b,
	0xee, 0x48, 0x0e, 0x52, 0xd4, 0xf1, 0xd9, 0x79, 0xa6, 0x82, 0x9f, 0x5c, 0x07, 0x89, 0x4c, 0x7e,
	0x3a, 0x30, 0x8f, 0x95, 0xf5, 0xf7, 0x4c, 0x22, 0x49, 0xe6, 0x5b, 0x3b, 0x3f, 0xa6, 0x9d, 0xaa,
	0xf4, 0x0c, 0x76, 0x86, 0x74, 0xd6, 0xad, 0xa4, 0xbb, 0x2b, 0x88, 0x4c, 0x65, 0xd2, 0xfb, 0x54,
	0x26, 0x69, 0xd0, 0xf2, 0xad, 0x41, 0xe7, 0xb7, 0xe2, 0xd3, 0xb4, 0xc3, 0xf3, 0x85, 0xdc, 0xb5,
	0x13, 0xbf, 0x82, 0x87, 0x06, 0x85, 0x30, 0x4c, 0x3b, 0xa9, 0x3b, 0x1a, 0xbe, 0x63, 0xf1, 0x6d,
	0xd8, 0x1d, 0xc1, 0x67, 0x73, 0xad, 0x4c, 0x02, 0x3b, 0xd0, 0x94, 0x42, 0xba, 0xa1, 0x16, 0x9b,
	0x1b, 0x40, 0x5e, 0xe4, 0x1c, 0xc0, 0x86, 0x76, 0x72, 0x92, 0xbe, 0x8f, 0xb2, 0xd3, 0x7e, 0x08,
	0x10, 0xc5, 0xec, 0x7d, 0x70, 0x7d, 0x31, 0x8e, 0x9c, 0x93, 0x38, 0xbf, 0x81, 0xce, 0xb4, 0xa9,
	0x09, 0xfc, 0x10, 0x20, 0x7b, 0xc1, 0x25, 0x86, 0x00, 0x39, 0x89, 0xf3, 0xcf, 0x9a, 0x7a, 0xf3,
	0xa7, 0xa1, 0xbe, 0x84, 0xda, 0x40, 0xdd, 0x55, 0x0c, 0x54, 0x0f, 0x8a, 0x50, 0x15, 0xae, 0x33,
	0xd4, 0xa8, 0x92, 0x5f, 0xc3, 0xa2, 0xa7, 0xdf, 0x18, 0xa6, 0x09, 0xb6, 0x26, 0x26, 0x6f, 0xe1,
	0x9d, 0x77, 0x5a, 0xa2, 0xa9, 0x3a, 0xf9, 0x1a, 0x6a, 0x9e, 0x9a, 0xb6, 0xea, 0x14, 0xa7, 0xc2,
	0x15, 0x5e, 0x15, 0xa7, 0x25, 0x6a, 0x94, 0x31, 0x60, 0x5f, 0xcf, 0x1a, 0x35, 0xea, 0xa7, 0x02,
	0x16, 0x07, 0x2e, 0x06, 0x34, 0xea, 0x68, 0x99, 0x18, 0xcb, 0xea, 0x2c, 0xcb, 0xde, 0x94, 0xa5,
	0x51, 0x27, 0xc7, 0xd0, 0xec, 0x8f, 0xc7, 0x8b, 0xba, 0x7a, 0x34, 0xf7, 0x77, 0xa6, 0xe2, 0x4e,
	0x8c, 0xb0, 0xd3, 0x12, 0xcd, 0x9b, 0x61, 0xc1, 0xbe, 0x1a, 0x23, 0xea, 0x7e, 0x32, 0x55, 0x70,
	0x61, 0xc4, 0x60, 0xc1, 0x5a, 0x19, 0x5f, 0x6c, 0x6a, 0x2e, 0xd4, 0x95, 0xd1, 0xfa, 0x04, 0x29,
	0xcc, 0x54, 0x39, 0x2d, 0xe9, 0x89, 0x81, 0x41, 0x98, 0x1a, 0x17, 0xea, 0xfa, 0x32, 0x15, 0xa4,
	0x30, 0x4a, 0x30, 0x88, 0x56, 0x46, 0xb3, 0xbe, 0xa2, 0x8d, 0xba, 0xd4, 0x4c, 0x99, 0x15, 0x66,
	0x08, 0x9a, 0x69, 0x65, 0x34, 0x4b, 0xb4, 0x59, 0x73, 0x96, 0x59, 0x6f, 0xd2, 0x4c, 0x2b, 0x93,
	0x3f, 0xc1, 0x6a, 0x7f, 0x06, 0x63, 0x3a, 0x2d, 0xe5, 0xe4, 0x8b, 0xe9, 0xd8, 0x73, 0x18, 0x79,
	0x5a, 0xa2, 0x33, 0x1d, 0x91, 0xdf, 0xc1, 0x52, 0x3f, 0x4f, 0x89, 0xce, 0x92, 0xf2, 0xec, 0x4c,
	0x79, 0x9e, 0x22, 0xdc, 0x69, 0x89, 0x16, 0x4d, 0x9f, 0xd7, 0xf1, 0xd8, 0xa4, 0x1b, 0x84, 0xce,
	0x7f, 0xab, 0x6a, 0x92, 0x67, 0xfc, 0xfa, 0x6a, 0x82, 0x30, 0x5b, 0x93, 0x84, 0xc9, 0x7f, 0x77,
	0x64, 0x8c, 0x39, 0x98, 0x64, 0xcc, 0xf6, 0x1c, 0xc6, 0x18, 0xeb, 0x1c, 0x65, 0xbe, 0x99, 0xa0,
	0xcc, 0xd6, 0x6c, 0xca, 0x64, 0x86, 0x29, 0x67, 0x0e, 0x26, 0x39, 0xb3, 0x3d, 0x87, 0x33, 0xe3,
	0x90, 0x29, 0x69, 0x0e, 0x26, 0x49, 0xb3, 0x3d, 0x87, 0x34, 0x63, 0xd3, 0x94, 0x35, 0x27, 0xb3,
	0x58, 0xf3, 0xf9, 0x2d, 0xac, 0xc9, 0x5c, 0x14, 0x68, 0xf3, 0x2d, 0xb4, 0xae, 0x72, 0x1f, 0x97,
	0x86, 0x3c, 0x9b, 0x45, 0x3f, 0xf9, 0xcf, 0xcf, 0xd3, 0x12, 0x2d, 0x58, 0x20, 0x6c, 0xa6, 0xb9,
	0xeb, 0x73, 0x26, 0x46, 0xee, 0x7d, 0x91, 0xeb, 0xee, 0x6f, 0xb2, 0xee, 0x6e, 0xcc, 0x99, 0x17,
	0x13, 0x76, 0xa6, 0xbd, 0x7f, 0x9c, 0xd3, 0xde, 0x9a, 0x5a, 0x7b, 0x77, 0x69, 0xef, 0xcc, 0xe7,
	0xec, 0xfe, 0x7e, 0x31, 0xbb, 0xbf, 0x1f, 0xdd, 0xda, 0xdf, 0x99, 0xcf, 0x79, 0x0d, 0xbe, 0xf7,
	0x9f, 0xaa, 0xba, 0xcb, 0x4d, 0x7c, 0xd9, 0x92, 0x1a, 0x94, 0xcf, 0x3f, 0xd8, 0x25, 0xb2, 0x0c,
	0xcd, 0xde, 0x4d, 0x22, 0xd9, 0xf0, 0x24, 0x8e, 0x45, 0x6c, 0x5b, 0x64, 0x1b, 0xee, 0xd3, 0x11,
	0xc7, 0x2f, 0x92, 0x33, 0xee, 0x09, 0x9e, 0x04, 0x89, 0x64, 0xdc, 0xbb, 0xd1, 0xdb, 0x65, 0xb2,
	0x09, 0xeb, 0xd8, 0x08, 0x33, 0xf6, 0x2a, 0x64, 0x03, 0xee, 0x99, 0x46, 0x0f, 0x04, 0x7f, 0x29,
	0x92, 0x44, 0x6f, 0x2c, 0x90, 0x55, 0xb0, 0x5f, 0xb9, 0x71, 0x32, 0x70, 0xc3, 0x30, 0xe0, 0x7d,
	0x2d, 0xad, 0x92, 0x75, 0x20, 0x6f, 0x78, 0x30, 0x8c, 0x42, 0x36, 0x64, 0x5c, 0x32, 0x5f, 0xcb,
	0x6b, 0xe4, 0x3e, 0xac, 0x9d, 0x47, 0x2c, 0x76, 0xe5, 0xf8, 0x5b, 0x43, 0x6f, 0x2d, 0x62, 0xf4,
	0x2e, 0xbb, 0x3a, 0x12, 0xfc, 0x7d, 0xd0, 0xef, 0x8a, 0xdf, 0x8f, 0x44, 0x3c, 0x32, 0x89, 0xd7,
	0xc9, 0x03, 0xd8, 0xa0, 0xcc, 0x53, 0x5b, 0x67, 0xfc, 0x22, 0x16, 0xfd, 0x98, 0xa5, 0x19, 0x34,
	0xc8, 0x1a, 0xac, 0x3c, 0x77, 0xfd, 0xc3, 0xb8, 0x3f, 0xc2, 0x58, 0x46, 0x0c, 0xa4, 0x05, 0xf5,
	0xc3, 0x28, 0xd0, 0xab, 0x26, 0x62, 0xd1, 0x15, 0x5d, 0xe1, 0x33, 0x2d, 0x68, 0x69, 0x01, 0x8e,
	0x63, 0x2d, 0x58, 0x22, 0xf7, 0x60, 0xf9, 0xb9, 0xeb, 0xff, 0x41, 0x5f, 0x4d, 0xb4, 0xb0, 0x4d,
	0x76, 0x60, 0xab, 0x2b, 0xd2, 0xc3, 0xfc, 0x4e, 0xc4, 0xe3, 0x63, 0xd0, 0x1a, 0xcb, 0x68, 0xa6,
	0xdc, 0xaa, 0xb9, 0xac, 0x85, 0x36, 0x0a, 0xcf, 0xf8, 0xa5, 0x1b, 0x06, 0xfe, 0xa1, 0x17, 0x6a,
	0xe1, 0x0a, 0x0a, 0x31, 0xde, 0x77, 0x6e, 0x10, 0xa6, 0x80, 0x10, 0xb2, 0x02, 0x4b, 0x5d, 0x21,
	0x4f, 0x86, 0x91, 0x34, 0x50, 0xdf, 0x43, 0xa8, 0xcd, 0xc7, 0xfd, 0xc9, 0x75, 0x14, 0xc4, 0xa9,
	0xee, 0x2a, 0xe9, 0xc0, 0xaa, 0xf1, 0x7a, 0xe4, 0x86, 0xe1, 0x3b, 0xd7, 0xfb, 0xa0, 0x77, 0xd6,
	0x10, 0x02, 0x63, 0xf2, 0x4a, 0x5c, 0xa6, 0x06, 0xeb, 0x78, 0x36, 0x5d, 0x21, 0x29, 0x73, 0x7d,
	0xc1, 0x43, 0xe3, 0x7f, 0x03, 0x6b, 0xca, 0xca, 0x38, 0xe7, 0x2f, 0x85, 0xe7, 0x86, 0x69, 0x3c,
	0xa5, 0xd1, 0x21, 0x04, 0xda, 0x5d, 0xa1, 0x29, 0x1a, 0x6b, 0xd9, 0x7d, 0x3c, 0xb9, 0xf4, 0x08,
	0x8e, 0x83, 0xc4, 0x7d, 0x97, 0xd5, 0xb0, 0x49, 0xfe, 0x1f, 0x3e, 0x37, 0x0e, 0x8e, 0x42, 0x91,
	0x30, 0x1f, 0x47, 0x73, 0x10, 0xb3, 0x9e, 0x9b, 0x84, 0x63, 0x80, 0x1f, 0x60, 0x5d, 0x66, 0x68,
	0x17, 0x4e, 0x7e, 0x0b, 0x37, 0xde, 0xf0, 0x0f, 0x5c, 0x5c, 0xf1, 0x42, 0x1e, 0xdb, 0x7b, 0x7f,
	0xb1, 0xa0, 0x5d, 0xfc, 0xf5, 0x44, 0x6c, 0x68, 0x1d, 0x07, 0x89, 0x19, 0xb0, 0xcc, 0xb7, 0x4b,
	0x88, 0x60, 0xef, 0x86, 0xa7, 0x63, 0x98, 0xf9, 0xb6, 0x45, 0xda, 0x00, 0x63, 0xa4, 0xed, 0x32,
	0xc2, 0x93, 0x6d, 0x53, 0xf3, 0xf9, 0x6c, 0x57, 0x14, 0x6a, 0x26, 0x47, 0xc6, 0x65, 0xe0, 0xb9,
	0x68, 0xbd, 0x40, 0x9a, 0xb0, 0x68, 0x80, 0xb7, 0xab, 0x04, 0xa0, 0xa6, 0x8b, 0xb2, 0x6b, 0x7b,
	0xff, 0xb2, 0xa0, 0x95, 0xff, 0x9d, 0x45, 0xea, 0xb0, 0xd0, 0x15, 0x9c, 0x69, 0xaa, 0x61, 0x17,
	0xe8, 0x89, 0x8e, 0x29, 0x18, 0x81, 0xbe, 0x24, 0x60, 0x0e, 0xa6, 0x4f, 0x90, 0x60, 0x47, 0x03,
	0x97, 0xf7, 0x99, 0xaf, 0x59, 0xa5, 0xcc, 0x4c, 0x83, 0xa5, 0x1b, 0x8a, 0x55, 0xa8, 0xa9, 0xce,
	0x80, 0xb2, 0x21, 0x1e, 0xaa, 0x5d, 0x55, 0x75, 0xa0, 0x6a, 0x41, 0x5c, 0x43, 0xe6, 0x5c, 0x60,
	0xdb, 0x22, 0x63, 0x65, 0x61, 0x6f, 0x71, 0xef, 0x57, 0x0a, 0x41, 0x73, 0x96, 0x2a, 0xe9, 0x16,
	0xd4, 0xd3, 0x78, 0x76, 0x09, 0x4b, 0xc0, 0x40, 0xb6, 0x45, 0x16, 0xa1, 0x72, 0xc8, 0x6f, 0xec,
	0xf2, 0xde, 0x3f, 0x2c, 0x58, 0x2a, 0x7c, 0x83, 0x23, 0x9e, 0xe3, 0x00, 0x76, 0x09, 0x1b, 0x71,
	0xbc, 0xee, 0xe1, 0x99, 0x72, 0x19, 0xb8, 0xa1, 0x6d, 0x91, 0x25, 0x68, 0x64, 0xbd, 0x65, 0x97,
	0xb1, 0xbe, 0x6c, 0x99, 0xd3, 0xab, 0xa0, 0xde, 0x91, 0xe0, 0xd2, 0x0d, 0x38, 0xc3, 0x21, 0xb2,
	0x06, 0x2b, 0xb9, 0x0a, 0x02, 0x39, 0x78, 0x2d, 0x43, 0xbb, 0x4a, 0x3e, 0x83, 0x07, 0xb3, 0xe2,
	0xa4, 0x0a, 0xb5, 0xbd, 0x17, 0x50, 0x4f, 0xff, 0x9f, 0x61, 0x25, 0x78, 0xb6, 0x76, 0x89, 0x34,
	0xa0, 0xfa, 0x43, 0x1c, 0x48, 0x66, 0x5b, 0xea, 0xf8, 0x54, 0x1d, 0x76, 0x19, 0x9f, 0xf5, 0x71,
	0xd8, 0x15, 0x54, 0x39, 0xf4, 0x87, 0x01, 0xb7, 0x17, 0x54, 0xdd, 0x61, 0x68, 0x57, 0xf7, 0x2f,
	0xc0, 0x7e, 0x2b, 0x84, 0x69, 0x36, 0x16, 0x5f, 0x06, 0x1e, 0x23, 0xcf, 0x60, 0x31, 0x8a, 0x85,
	0xc7, 0x92, 0x84, 0xac, 0xcd, 0xbc, 0x5e, 0x6f, 0xae, 0xcf, 0xbe, 0x44, 0xec, 0x5a, 0xbf, 0xb4,
	0x9e, 0xff, 0x0c, 0x1e, 0x89, 0xb8, 0xff, 0xc4, 0x8d, 0x5c, 0x6f, 0xc0, 0x72, 0x7a, 0xfd, 0x38,
	0xf2, 0x9e, 0xf4, 0x19, 0xc7, 0x41, 0xc8, 0xfc, 0x0b, 0xeb, 0x5d, 0x4d, 0xfd, 0xa6, 0xfd, 0xf2,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21, 0x13, 0x0a, 0xce, 0xb9, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZooKeeperServiceClient is the client API for ZooKeeperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZooKeeperServiceClient interface {
	Process(ctx context.Context, opts ...grpc.CallOption) (ZooKeeperService_ProcessClient, error)
}

type zooKeeperServiceClient struct {
	cc *grpc.ClientConn
}

func NewZooKeeperServiceClient(cc *grpc.ClientConn) ZooKeeperServiceClient {
	return &zooKeeperServiceClient{cc}
}

func (c *zooKeeperServiceClient) Process(ctx context.Context, opts ...grpc.CallOption) (ZooKeeperService_ProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ZooKeeperService_serviceDesc.Streams[0], "/zookeeper.ZooKeeperService/process", opts...)
	if err != nil {
		return nil, err
	}
	x := &zooKeeperServiceProcessClient{stream}
	return x, nil
}

type ZooKeeperService_ProcessClient interface {
	Send(*RpcRequest) error
	Recv() (*RpcResponse, error)
	grpc.ClientStream
}

type zooKeeperServiceProcessClient struct {
	grpc.ClientStream
}

func (x *zooKeeperServiceProcessClient) Send(m *RpcRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *zooKeeperServiceProcessClient) Recv() (*RpcResponse, error) {
	m := new(RpcResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ZooKeeperServiceServer is the server API for ZooKeeperService service.
type ZooKeeperServiceServer interface {
	Process(ZooKeeperService_ProcessServer) error
}

// UnimplementedZooKeeperServiceServer can be embedded to have forward compatible implementations.
type UnimplementedZooKeeperServiceServer struct {
}

func (*UnimplementedZooKeeperServiceServer) Process(srv ZooKeeperService_ProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}

func RegisterZooKeeperServiceServer(s *grpc.Server, srv ZooKeeperServiceServer) {
	s.RegisterService(&_ZooKeeperService_serviceDesc, srv)
}

func _ZooKeeperService_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZooKeeperServiceServer).Process(&zooKeeperServiceProcessServer{stream})
}

type ZooKeeperService_ProcessServer interface {
	Send(*RpcResponse) error
	Recv() (*RpcRequest, error)
	grpc.ServerStream
}

type zooKeeperServiceProcessServer struct {
	grpc.ServerStream
}

func (x *zooKeeperServiceProcessServer) Send(m *RpcResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *zooKeeperServiceProcessServer) Recv() (*RpcRequest, error) {
	m := new(RpcRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ZooKeeperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zookeeper.ZooKeeperService",
	HandlerType: (*ZooKeeperServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "process",
			Handler:       _ZooKeeperService_Process_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zookeeper.proto",
}
